import z from "zod";

const reverseKV = (obj: object) =>
  Object.fromEntries(Object.entries(obj).map(([a, b]) => [b, a]));

export const MOVIE_TO_ID = {
  "A Friend of Dorothy": 1470465,
  "All the Empty Rooms": 1525091,
  "Armed Only with a Camera: The Life and Death of Brent Renaud": 1422051,
  "Avatar: Fire and Ash": 83533,
  "Blue Moon": 1299655,
  "Children No More: Were and Are Gone": 1560400,
  "Come See Me in the Good Light": 1400780,
  "Cutting Through Rocks": 1400793,
  "Diane Warren: Relentless": 826338,
  "It Was Just an Accident": 1456349,
  "Jurassic World Rebirth": 1234821,
  "K-Pop: Demon Hunters": 803796,
  "Little Amélie or The Character of Rain": 682012,
  "Marty Supreme": 1317288,
  "Mr. Nobody Against Putin": 1393151,
  "One Battle After Another": 1054867,
  "Perfectly a Strangeness": 1278954,
  "Retirement Plan": 1316745,
  "Sentimental Value": 1124566,
  "Song Sung Blue": 1371185,
  "The Alabama Solution": 1413805,
  "The Devil Is Busy": 1373150,
  "The Girl Who Cried Pearls": 1142149,
  "The Lost Bus": 1236470,
  "The Perfect Neighbor": 1400782,
  "The Secret Agent": 1220564,
  "The Singers": 1442908,
  "The Smashing Machine": 760329,
  "The Three Sisters": 1302562,
  "The Ugly Stepsister": 1284120,
  "The Voice of Hind Rajab": 1480382,
  "Train Dreams": 1241983,
  "Two People Exchanging Saliva": 1340625,
  "Viva Verdi!": 1358554,
  "Zootopia 2": 1084242,
  "Butcher's Stain": 1560394,
  "If I Had Legs I'd Kick You": 1160360,
  "Jane Austen's Period Drama": 1272266,
  Arco: 804370,
  Bugonia: 701387,
  Butterfly: 1233361,
  Elio: 1022787,
  F1: 911430,
  Forevergreen: 1477914,
  Frankenstein: 1062722,
  Hamnet: 858024,
  Kokuho: 1379266,
  Sinners: 1233413,
  Sirât: 1151272,
  Weapons: 1078605,
} as const;

export const NOMINEE_TO_ID = {
  "Timothée Chalamet": 1190668,
  "Leonardo DiCaprio": 6193,
  "Ethan Hawke": 569,
  "Michael B. Jordan": 135651,
  "Wagner Moura": 52583,
  "Jessie Buckley": 1498158,
  "Rose Byrne": 9827,
  "Kate Hudson": 11661,
  "Renate Reinsve": 1576786,
  "Emma Stone": 54693,
  "Benicio del Toro": 1121,
  "Jacob Elordi": 2034418,
  "Delroy Lindo": 18792,
  "Sean Penn": 2228,
  "Stellan Skarsgård": 1640,
  "Elle Fanning": 18050,
  "Inga Ibsdotter Lilleaas": 1421850,
  "Amy Madigan": 23882,
  "Wunmi Mosaku": 134774,
  "Teyana Taylor": 964679,
} as const;

export const MOVIE_TO_EMOJI = {
  "A Friend of Dorothy": "🏳️‍🌈",
  "All the Empty Rooms": "🧸",
  "Armed Only with a Camera: The Life and Death of Brent Renaud": "📷",
  "Avatar: Fire and Ash": "🔥",
  "Blue Moon": "🎹",
  "Children No More: Were and Are Gone": "🕯️",
  "Come See Me in the Good Light": "🎤",
  "Cutting Through Rocks": "🇮🇷",
  "Diane Warren: Relentless": "🎼",
  "It Was Just an Accident": "🚗",
  "Jurassic World Rebirth": "🦖",
  "K-Pop: Demon Hunters": "💃",
  "Little Amélie or The Character of Rain": "🌧️",
  "Marty Supreme": "🏓",
  "Mr. Nobody Against Putin": "🇷🇺",
  "One Battle After Another": "🏃‍♂️‍➡️",
  "Perfectly a Strangeness": "🫏",
  "Retirement Plan": "📝",
  "Sentimental Value": "🎭",
  "Song Sung Blue": "💎",
  "The Alabama Solution": "⛓️",
  "The Devil Is Busy": "🏥",
  "The Girl Who Cried Pearls": "🐚",
  "The Lost Bus": "🚌",
  "The Perfect Neighbor": "🏘️",
  "The Secret Agent": "🕵️‍♂️",
  "The Singers": "🎶",
  "The Smashing Machine": "🥊",
  "The Three Sisters": "🏝️",
  "The Ugly Stepsister": "👠",
  "The Voice of Hind Rajab": "📞",
  "Train Dreams": "🌲",
  "Two People Exchanging Saliva": "💋",
  "Viva Verdi!": "🏰",
  "Zootopia 2": "🐰",
  "Butcher's Stain": "🔪",
  "If I Had Legs I'd Kick You": "🦵",
  "Jane Austen's Period Drama": "🩸",
  Arco: "🌈",
  Bugonia: "👽",
  Butterfly: "🏊",
  Elio: "🌌",
  F1: "🏎️",
  Forevergreen: "🌳",
  Frankenstein: "🧟",
  Hamnet: "🖋️",
  Kokuho: "👘",
  Sinners: "🧛",
  Sirât: "🔊",
  Weapons: "🚸",
} as const;

export const EMOJI_TO_MOVIE = reverseKV(MOVIE_TO_EMOJI);

export const NOMINEE_TO_EMOJI = {
  "Actor in a Leading Role": {
    "Timothée Chalamet": "🏓",
    "Leonardo DiCaprio": "🏃",
    "Ethan Hawke": "🥃",
    "Michael B. Jordan": "👥",
    "Wagner Moura": "🫥",
  },
  "Actress in a Leading Role": {
    "Jessie Buckley": "🌿",
    "Rose Byrne": "🤱",
    "Kate Hudson": "🎤",
    "Renate Reinsve": "🎭",
    "Emma Stone": "👩‍🦲",
  },
  "Actor in a Supporting Role": {
    "Benicio del Toro": "🥋",
    "Jacob Elordi": "🔩",
    "Delroy Lindo": "🎹",
    "Sean Penn": "⚖️",
    "Stellan Skarsgård": "🎬",
  },
  "Actress in a Supporting Role": {
    "Elle Fanning": "👩‍👩‍👧",
    "Inga Ibsdotter Lilleaas": "👧",
    "Amy Madigan": "🧹",
    "Wunmi Mosaku": "🪴",
    "Teyana Taylor": "🐀",
  },
} as const;

export const EMOJI_TO_NOMINEE = Object.fromEntries(
  Object.entries(NOMINEE_TO_EMOJI).map(([a, b]) => [a, reverseKV(b)]),
);

export const CATEGORIES = {
  "Best Picture": [
    "Bugonia",
    "F1",
    "Frankenstein",
    "Hamnet",
    "Marty Supreme",
    "One Battle After Another",
    "The Secret Agent",
    "Sentimental Value",
    "Sinners",
    "Train Dreams",
  ],
  Directing: {
    "Paul Thomas Anderson": "One Battle After Another",
    "Ryan Coogler": "Sinners",
    "Josh Safdie": "Marty Supreme",
    "Joachim Trier": "Sentimental Value",
    "Chloé Zhao": "Hamnet",
  },
  "Actor in a Leading Role": {
    "Timothée Chalamet": "Marty Supreme",
    "Leonardo DiCaprio": "One Battle After Another",
    "Ethan Hawke": "Blue Moon",
    "Michael B. Jordan": "Sinners",
    "Wagner Moura": "The Secret Agent",
  },
  "Actress in a Leading Role": {
    "Jessie Buckley": "Hamnet",
    "Rose Byrne": "If I Had Legs I'd Kick You",
    "Kate Hudson": "Song Sung Blue",
    "Renate Reinsve": "Sentimental Value",
    "Emma Stone": "Bugonia",
  },
  "Actor in a Supporting Role": {
    "Benicio del Toro": "One Battle After Another",
    "Jacob Elordi": "Frankenstein",
    "Delroy Lindo": "Sinners",
    "Sean Penn": "One Battle After Another",
    "Stellan Skarsgård": "Sentimental Value",
  },
  "Actress in a Supporting Role": {
    "Elle Fanning": "Sentimental Value",
    "Inga Ibsdotter Lilleaas": "Sentimental Value",
    "Amy Madigan": "Weapons",
    "Wunmi Mosaku": "Sinners",
    "Teyana Taylor": "One Battle After Another",
  },
  "Original Screenplay": [
    "Blue Moon",
    "It Was Just an Accident",
    "Marty Supreme",
    "Sentimental Value",
    "Sinners",
  ],
  "Adapted Screenplay": [
    "Bugonia",
    "Frankenstein",
    "Hamnet",
    "One Battle After Another",
    "Train Dreams",
  ],
  "Animated Feature Film": [
    "Arco",
    "Elio",
    "K-Pop: Demon Hunters",
    "Little Amélie or The Character of Rain",
    "Zootopia 2",
  ],
  "International Feature Film": [
    "It Was Just an Accident",
    "The Secret Agent",
    "Sentimental Value",
    "Sirât",
    "The Voice of Hind Rajab",
  ],
  "Documentary Feature Film": [
    "The Alabama Solution",
    "Come See Me in the Good Light",
    "Cutting Through Rocks",
    "Mr. Nobody Against Putin",
    "The Perfect Neighbor",
  ],
  Cinematography: [
    "Frankenstein",
    "Marty Supreme",
    "One Battle After Another",
    "Sinners",
    "Train Dreams",
  ],
  "Film Editing": [
    "F1",
    "Marty Supreme",
    "One Battle After Another",
    "Sentimental Value",
    "Sinners",
  ],
  "Original Score": [
    "Bugonia",
    "Frankenstein",
    "Hamnet",
    "One Battle After Another",
    "Sinners",
  ],
  "Original Song": {
    "Dear Me": "Diane Warren: Relentless",
    Golden: "K-Pop: Demon Hunters",
    "I Lied To You": "Sinners",
    "Sweet Dreams of Joy": "Viva Verdi!",
    "Train Dreams": "Train Dreams",
  },
  "Production Design": [
    "Frankenstein",
    "Hamnet",
    "Marty Supreme",
    "One Battle After Another",
    "Sinners",
  ],
  "Costume Design": [
    "Avatar: Fire and Ash",
    "Frankenstein",
    "Hamnet",
    "Marty Supreme",
    "Sinners",
  ],
  "Makeup and Hairstyling": [
    "Frankenstein",
    "Kokuho",
    "Sinners",
    "The Smashing Machine",
    "The Ugly Stepsister",
  ],
  Sound: ["F1", "Frankenstein", "One Battle After Another", "Sinners", "Sirât"],
  "Visual Effects": [
    "Avatar: Fire and Ash",
    "F1",
    "Jurassic World Rebirth",
    "The Lost Bus",
    "Sinners",
  ],
  Casting: [
    "Hamnet",
    "Marty Supreme",
    "One Battle After Another",
    "The Secret Agent",
    "Sinners",
  ],
  "Live Action Short Film": [
    "Butcher's Stain",
    "A Friend of Dorothy",
    "Jane Austen's Period Drama",
    "The Singers",
    "Two People Exchanging Saliva",
  ],
  "Animated Short Film": [
    "Butterfly",
    "Forevergreen",
    "The Girl Who Cried Pearls",
    "Retirement Plan",
    "The Three Sisters",
  ],
  "Documentary Short Film": [
    "All the Empty Rooms",
    "Armed Only with a Camera: The Life and Death of Brent Renaud",
    "Children No More: Were and Are Gone",
    "The Devil Is Busy",
    "Perfectly a Strangeness",
  ],
} as const;

export const BallotForm = z.object({
  "Best Picture": z.number(),
  Directing: z.number(),
  "Actor in a Leading Role": z.number(),
  "Actress in a Leading Role": z.number(),
  "Actor in a Supporting Role": z.number(),
  "Actress in a Supporting Role": z.number(),
  "Original Screenplay": z.number(),
  "Adapted Screenplay": z.number(),
  "Animated Feature Film": z.number(),
  "International Feature Film": z.number(),
  "Documentary Feature Film": z.number(),
  Cinematography: z.number(),
  "Film Editing": z.number(),
  "Original Score": z.number(),
  "Original Song": z.number(),
  "Production Design": z.number(),
  "Costume Design": z.number(),
  "Makeup and Hairstyling": z.number(),
  Sound: z.number(),
  Casting: z.number(),
  "Live Action Short Film": z.number(),
  "Animated Short Film": z.number(),
  "Documentary Short Film": z.number(),
});
